server:
  port: 8081
  servlet:
    context-path: /bibliotecainfantil

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://mhxdadnmnpuind:ae7c4c217a55dd98c1cdec701d544c577b7923b9332aa110ee89acf25c9a8f1b@ec2-107-23-135-132.compute-1.amazonaws.com:5432/d1c162ade7aahv
    username: mhxdadnmnpuind
    password: ae7c4c217a55dd98c1cdec701d544c577b7923b9332aa110ee89acf25c9a8f1b
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none


application:
  description: Controle de Livros de Escola Infantil
