server:
  port: 8081
  servlet:
    context-path: /bibliotecainfantil

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/biblioteca
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update


application:
  description: Controle de Livros de Escola Infantil
